Develop
zh-dmit/Sprint_4 pull request #1
Opened 2024-11-18 10:57 UTC by zh-dmit

Реализация проекта 4го спринта

2024-11-18 14:02 UTC, digranate approved these changes
Работа отличная! Все тесты реализованы. Применена параметризация. 
можно было бы увидеть и доп задание) 

зачет!

2024-11-18 14:02 UTC, pomegranate282922 commented on src/main/java/org/example/Main.java
> +public class Main {
Этот класс лишний  
Можно улучшить

2024-11-18 14:02 UTC, digranate commented on src/test/java/ChecksMainPageTest.java
> +        driver.get("https://qa-scooter.praktikum-services.ru/");
Урлы лучше вынести как константы 
Можно улучшить

2024-11-18 14:02 UTC, digranate commented on src/test/java/ChecksMainPageTest.java
> +    public void closeDriver() {
Общие начала и концы всех тестовых классов удобно вынести в класс предок 
Можно улучшить

2024-11-18 14:02 UTC, digranate commented on src/test/java/ChecksOrderPageTest.java
> +    String name;
Лучше приватные

2024-11-18 14:02 UTC, digranate commented on src/main/java/org/example/MainPageObject.java
> +public class MainPageObject extends BasePageObject {
Отлично что есть иерархия page object

2024-11-22 17:59 UTC, zh-dmit commented on src/main/java/org/example/Main.java
> +public class Main {
поправил

2024-11-22 17:59 UTC, zh-dmit commented on src/test/java/ChecksMainPageTest.java
> +        driver.get("https://qa-scooter.praktikum-services.ru/");
поправил

2024-11-22 17:59 UTC, zh-dmit commented on src/test/java/ChecksMainPageTest.java
> +    public void closeDriver() {
поправил

2024-11-22 17:59 UTC, zh-dmit commented on src/test/java/ChecksOrderPageTest.java
> +    String name;
поправил

2024-11-23 16:30 UTC, vrnsky requested changes

2024-11-23 16:30 UTC, vrnsky commented on pom.xml
> +    <version>1.0-SNAPSHOT</version>
Поменять версию, версия должна следовать правилам semantic version. Major.Minor.Patch, то есть 0.0.1-SNAPSHOT

2024-11-23 16:30 UTC, vrnsky commented on pom.xml
> +            <artifactId>junit</artifactId>
Используй JUnit 5-ой версии, потому что четвертая уже out-of-date

2024-11-23 16:30 UTC, vrnsky commented on src/main/java/org/example/BasePageObject.java
> +package org.example;
Нейминг пакетов, com.example - это для примеров. Надо ru.zheka.penis

2024-11-23 16:30 UTC, vrnsky commented on src/main/java/org/example/MainPageObject.java
> +public class MainPageObject extends BasePageObject {
Добавь логгирование, чтобы можно было отследить что в тестах происходило

2024-11-23 16:30 UTC, vrnsky commented on src/main/java/org/example/MainPageObject.java
> +    //Кнопка принятия куки
Переделать комментарий в стиле JavaDoc, чтобы потом по ним можно было генерировать документацию

2024-11-23 16:30 UTC, vrnsky commented on src/test/java/ChecksErrorForOrderTests.java
> +        final String positionButton = "кнопка вверху";
final не обязателен

2024-11-29 04:13 UTC, vrnsky approved these changes

2025-01-16 19:59 UTC, closed without merging